
SEED_FOODS = [
    # ── INDIAN VEGETARIAN ──────────────────────────────────────────────────────
  {
    "name": "Dal Makhani",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 150,
    "protein": 6.0,
    "fat": 8.0,
    "carbs": 14.0,
    "tags": ["vegetarian", "savory", "creamy", "gluten-free", "dairy"],
    "description": "Rich black lentil curry slow-cooked with butter and cream.",
    "image": "/images/1200-by-1200-images-1.jpg",
    "why_healthy": "Good source of protein and fibre, though relatively high in fat"
  },
  
  {
    "name": "Palak Paneer",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 140,
    "protein": 7.0,
    "fat": 10.0,
    "carbs": 6.0,
    "tags": ["vegetarian", "savory", "gluten-free", "dairy", "high-protein"],
    "description": "Spinach and cottage cheese curry with aromatic spices.",
    "image": "/images/Saag-Paneer-FF-500x500.jpg",
    "why_healthy": "Rich in iron, calcium, and protein"
  },
  {
    "name": "Masala Dosa",
    "category": "breakfast",
    "cuisine": "Indian",
    "calories": 180,
    "protein": 4.0,
    "fat": 6.0,
    "carbs": 28.0,
    "tags": ["vegetarian", "vegan-optional", "savory", "crispy", "dairy-free"],
    "description": "Crispy fermented rice crepe filled with spiced potato masala.",
    "image": "/images/Masala-Dosa-500x500.webp",
    "why_healthy": "Fermented batter supports digestion"
  },
  {
    "name": "Idli Sambar",
    "category": "breakfast",
    "cuisine": "Indian",
    "calories": 100,
    "protein": 4.0,
    "fat": 1.5,
    "carbs": 18.0,
    "tags": ["vegetarian", "vegan", "light", "low-fat", "gluten-free", "dairy-free"],
    "description": "Steamed rice cakes served with lentil vegetable soup.",
    "image": "/images/idli-sambar-900x600.jpg",
    "why_healthy": "Low fat and easy to digest"
  },
  {
    "name": "Chana Masala",
    "category": "lunch",
    "cuisine": "Indian",
    "calories": 160,
    "protein": 7.0,
    "fat": 4.0,
    "carbs": 23.0,
    "tags": ["vegetarian", "vegan", "spicy", "savory", "gluten-free", "dairy-free", "high-protein"],
    "description": "Spiced chickpea curry with tangy tomato-onion gravy.",
    "image": "images/easy-chana-masala-pan-1024x1536.jpg",
    "why_healthy": "High in plant protein and fibre"
  },
  {
    "name": "Rajma Chawal",
    "category": "lunch",
    "cuisine": "Indian",
    "calories": 140,
    "protein": 5.0,
    "fat": 2.5,
    "carbs": 25.0,
    "tags": ["vegetarian", "vegan", "savory", "gluten-free", "dairy-free"],
    "description": "Kidney bean curry served with rice.",
    "image": "/images/rajma-chawal-1-500x500.jpg",
    "why_healthy": "Balanced protein and complex carbohydrates"
  },
  {
    "name": "Aloo Gobi",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 120,
    "protein": 3.0,
    "fat": 5.0,
    "carbs": 16.0,
    "tags": ["vegetarian", "vegan", "savory", "gluten-free", "dairy-free"],
    "description": "Potato and cauliflower cooked with spices.",
    "image": "/images/aloo-gobi.jpg",
    "why_healthy": "Contains fibre and vitamin C"
  },
  {
    "name": "Baingan Bharta",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 110,
    "protein": 2.5,
    "fat": 5.0,
    "carbs": 13.0,
    "tags": ["vegetarian", "vegan", "smoky", "savory", "gluten-free", "dairy-free"],
    "description": "Roasted eggplant mash cooked with spices.",
    "image": "/images/FB-Thumnails-website-old-96.jpg",
    "why_healthy": "Low calorie and rich in antioxidants"
  },
  {
    "name": "Matar Paneer",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 170,
    "protein": 7.0,
    "fat": 11.0,
    "carbs": 10.0,
    "tags": ["vegetarian", "savory", "creamy", "gluten-free", "dairy"],
    "description": "Peas and paneer in spiced gravy.",
    "image": "/images/Matar-Paneer-500x500.jpg",
    "why_healthy": "Provides protein and fibre"
  },
  {
    "name": "Poha",
    "category": "breakfast",
    "cuisine": "Indian",
    "calories": 130,
    "protein": 2.5,
    "fat": 3.5,
    "carbs": 22.0,
    "tags": ["vegetarian", "vegan-optional", "light", "savory", "gluten-free", "dairy-free"],
    "description": "Flattened rice cooked with spices and peanuts.",
    "image": "/images/poha-indian-breakfast-recipe.jpg",
    "why_healthy": "Light and easy to digest"
  },
  {
    "name": "Upma",
    "category": "breakfast",
    "cuisine": "Indian",
    "calories": 140,
    "protein": 3.5,
    "fat": 4.0,
    "carbs": 22.0,
    "tags": ["vegetarian", "savory", "contains-gluten"],
    "description": "Semolina dish cooked with vegetables.",
    "image": "/images/Vegetable-Upma-3.jpg",
    "why_healthy": "Provides steady energy"
  },
  {
    "name": "Methi Thepla",
    "category": "breakfast",
    "cuisine": "Indian",
    "calories": 180,
    "protein": 5.0,
    "fat": 7.0,
    "carbs": 24.0,
    "tags": ["vegetarian", "savory", "contains-gluten"],
    "description": "Fenugreek flatbread made from wheat flour.",
    "image": "/images/methi-thepla.jpg",
    "why_healthy": "Contains fibre and beneficial plant compounds"
  },
  {
    "name": "Pav Bhaji",
    "category": "lunch",
    "cuisine": "Indian",
    "calories": 200,
    "protein": 3.5,
    "fat": 8.0,
    "carbs": 28.0,
    "tags": ["vegetarian", "savory", "spicy", "dairy"],
    "description": "Mashed vegetable curry served with bread.",
    "image": "/images/Instant-Pot-Mumbai-Pav-Bhaji-Recipe.jpg",
    "why_healthy": "Contains vegetables but can be high in butter"
  },
  {
    "name": "Bhindi Masala",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 120,
    "protein": 2.5,
    "fat": 5.0,
    "carbs": 14.0,
    "tags": ["vegetarian", "vegan", "savory", "gluten-free", "dairy-free"],
    "description": "Okra cooked with spices and onions.",
    "image": "/images/punjabi_bhindi_masala_gravy_featured.jpg",
    "why_healthy": "Rich in fibre and micronutrients"
  },

    # ── INDIAN NON-VEGETARIAN ────
  {
    "name": "Chicken Tikka Masala",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 420,
    "protein": 30.0,
    "fat": 22.0,
    "carbs": 18.0,
    "tags": ["non-vegetarian", "spicy", "savory", "creamy", "gluten-free", "high-protein"],
    "description": "Grilled chicken cooked in a creamy spiced tomato-based sauce.",
    "image":"/images/Chicken-tikka-masala-735x980.jpg",
    "why_healthy": "High protein, but moderately high in fat due to cream"
  },
  {
    "name": "Chicken Biryani",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 500,
    "protein": 26.0,
    "fat": 18.0,
    "carbs": 60.0,
    "tags": ["non-vegetarian", "savory", "aromatic", "spicy", "gluten-free"],
    "description": "Fragrant basmati rice cooked with marinated chicken and spices.",
    "image":"/images/Hyderabadi-Chicken-Biryani-Recipe-1.png.webp",
    "why_healthy": "Balanced meal but calorie-dense due to rice and oil"
  },
  {
    "name": "Fish Curry",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 280,
    "protein": 25.0,
    "fat": 14.0,
    "carbs": 10.0,
    "tags": ["non-vegetarian", "spicy", "savory", "gluten-free", "high-protein"],
    "description": "Fish cooked in spiced coconut or tamarind-based gravy.",
    "image":"/images/thumb__1200_0_0_0_auto.jpg",
    "why_healthy": "Rich in omega-3 fatty acids and lean protein"
  },
  {
    "name": "Egg Bhurji",
    "category": "breakfast",
    "cuisine": "Indian",
    "calories": 220,
    "protein": 14.0,
    "fat": 15.0,
    "carbs": 6.0,
    "tags": ["non-vegetarian", "spicy", "savory", "gluten-free", "high-protein"],
    "description": "Scrambled eggs cooked with onions, tomatoes, and spices.",
    "image":"/images/egg-bhurji-1.webp",
    "why_healthy": "High quality protein and essential vitamins"
  },
  {
    "name": "Mutton Rogan Josh",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 520,
    "protein": 32.0,
    "fat": 35.0,
    "carbs": 10.0,
    "tags": ["non-vegetarian", "spicy", "savory", "aromatic", "gluten-free", "high-protein"],
    "description": "Slow-cooked lamb in rich Kashmiri spices.",
    "image":"/images/Rogan_Josh_Kashmiri.jpg",
    "why_healthy": "High protein and iron, but high in saturated fat"
  },
  {
    "name": "Prawn Masala",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 300,
    "protein": 28.0,
    "fat": 12.0,
    "carbs": 12.0,
    "tags": ["non-vegetarian", "spicy", "savory", "gluten-free", "high-protein"],
    "description": "Prawns cooked in spicy onion-tomato gravy.",
    "image":"/images/Shrimp-Masala-2-3.jpg",
    "why_healthy": "Low fat, high protein seafood rich in minerals"
  },
  {
    "name": "Keema Matar",
    "category": "dinner",
    "cuisine": "Indian",
    "calories": 380,
    "protein": 28.0,
    "fat": 24.0,
    "carbs": 14.0,
    "tags": ["non-vegetarian", "spicy", "savory", "gluten-free", "high-protein"],
    "description": "Minced meat cooked with peas and aromatic spices.",
    "image":"/images/d46e2a617196a2fc89c215fb61dfa701_Soya_Keema_Matar__-_Plating.jpg",
    "why_healthy": "High protein and iron, but moderately high fat"
  },

    # ── WESTERN DISHES ────────────
  {
    "name": "Caesar Salad",
    "category": "lunch",
    "cuisine": "Western",
    "calories": 250,
    "protein": 12.0,
    "fat": 14.0,
    "carbs": 18.0,
    "tags": ["vegetarian", "savory", "light", "dairy","Mexican"],
    "description": "Crisp romaine with parmesan, croutons, and Caesar dressing.",
    "image": "/images/caesar-salad.jpg",
    "why_healthy": "Low calorie, rich in vitamins A and K"
  },
  {
    "name": "Grilled Chicken Salad",
    "category": "lunch",
    "cuisine": "Western",
    "calories": 280,
    "protein": 28.0,
    "fat": 9.0,
    "carbs": 12.0,
    "tags": ["non-vegetarian", "savory", "light", "gluten-free", "USA" , "high-protein"],
    "description": "Lean grilled chicken breast over mixed greens with vinaigrette.",
   "image": "/images/Grilled-Chicken-Salad-min.jpg",
    "why_healthy": "High protein and low calorie"
  },
  {
    "name": "Quinoa Power Bowl",
    "category": "lunch",
    "cuisine": "Western",
    "calories": 340,
    "protein": 16.0,
    "fat": 10.0,
    "carbs": 48.0,
    "tags": ["vegetarian", "vegan", "savory", "gluten-free", "Andean region of South America" ,"dairy-free", "high-protein"],
    "description": "Quinoa with roasted veggies, chickpeas, and tahini dressing.",
    "image": "/images/red_quinoa_power_bfast_bowl.jpg",
    "why_healthy": "Complete plant protein with essential amino acids"
  },
  {
    "name": "Avocado Toast",
    "category": "breakfast",
    "cuisine": "Western",
    "calories": 290,
    "protein": 9.0,
    "fat": 18.0,
    "carbs": 28.0,
    "tags": ["vegetarian", "vegan", "savory", "Australia","dairy-free"],
    "description": "Crushed avocado on sourdough with lemon and chilli flakes.",
    "image": "/images/Bean-avocado-toast-3.jpg",
    "why_healthy": "Rich in heart-healthy monounsaturated fats"
  },
  {
    "name": "Greek Salad",
    "category": "lunch",
    "cuisine": "Mediterranean",
    "calories": 200,
    "protein": 8.0,
    "fat": 12.0,
    "carbs": 16.0,
    "tags": ["vegetarian", "light", "Greece","savory", "gluten-free", "dairy"],
    "description": "Cucumber, tomato, olives, and feta cheese in olive oil.",
    "image": "/images/IG3.png",
    "why_healthy": "Healthy fats from olive oil and olives"
  },
  {
    "name": "Pasta Primavera",
    "category": "dinner",
    "cuisine": "Western",
    "calories": 400,
    "protein": 12.0,
    "fat": 9.0,
    "carbs": 64.0,
    "tags": ["vegetarian", "Italian-American","savory"],
    "description": "Penne with seasonal vegetables in garlic olive oil sauce.",
    "image": "/images/Pasta-Primavera-3.jpg",
    "why_healthy": "Rich in fiber and micronutrients from vegetables"
  },
  {
    "name": "Margherita Pizza",
    "category": "dinner",
    "cuisine": "Western",
    "calories": 420,
    "protein": 14.0,
    "fat": 13.0,
    "carbs": 58.0,
    "tags": ["vegetarian",  "Italy","savory", "dairy"],
    "description": "Classic pizza with tomato sauce, fresh mozzarella, and basil.",
    "image": "/images/margherita-pizza-resize-8-1.jpg",
    "why_healthy": "Tomatoes provide lycopene antioxidants"
  },
  {
    "name": "Veggie Burger",
    "category": "lunch",
    "cuisine": "Western",
    "calories": 410,
    "protein": 16.0,
    "fat": 14.0,
    "carbs": 48.0,
    "tags": ["vegetarian", "vegan", "London(UK)","savory", "dairy-free"],
    "description": "Black bean and sweet potato patty with fresh toppings.",
    "image": "/images/VEG Burger.jpg",
    "why_healthy": "High plant protein and fiber"
  },
  {
    "name": "Grilled Salmon",
    "category": "dinner",
    "cuisine": "Western",
    "calories": 320,
    "protein": 34.0,
    "fat": 16.0,
    "carbs": 2.0,
    "tags": ["non-vegetarian", "Norway","savory", "gluten-free", "dairy-free", "high-protein"],
    "description": "Herb-seasoned salmon fillet grilled to perfection.",
    "image": "/images/Grilled Salmon.webp",
    "why_healthy": "Rich in omega-3 fatty acids and vitamin D"
  },
  {
    "name": "Mushroom Risotto",
    "category": "dinner",
    "cuisine": "Western",
    "calories": 380,
    "protein": 10.0,
    "fat": 12.0,
    "carbs": 54.0,
    "tags": ["vegetarian","Italy", "savory", "creamy", "gluten-free", "dairy"],
    "description": "Creamy Arborio rice with wild mushrooms and parmesan.",
    "image": "/images/Risotto-Mushroom-2-352.jpg",
    "why_healthy": "Mushrooms provide B vitamins and antioxidants"
  },
  {
    "name": "Greek Yogurt Parfait",
    "category": "breakfast",
    "cuisine": "Western",
    "calories": 220,
    "protein": 16.0,
    "fat": 4.0,
    "carbs": 32.0,
    "tags": ["vegetarian","France", "sweet", "light", "gluten-free", "dairy", "high-protein"],
    "description": "Greek yogurt layered with granola, berries, and honey.",
    "image": "/images/yogurt-parfait-4.jpg",
    "why_healthy": "Probiotics and antioxidants"
  },
  {
    "name": "Smoothie Bowl",
    "category": "breakfast",
    "cuisine": "Western",
    "calories": 280,
    "protein": 10.0,
    "fat": 6.0,
    "carbs": 52.0,
    "tags": ["vegetarian","Brazil", "vegan", "sweet", "light", "gluten-free", "dairy-free"],
    "description": "Blended fruit base topped with seeds and fresh fruits.",
    "image": "/images/Smoothie-Bowl-Overhead-500x500.jpg",
    "why_healthy": "High in antioxidants and fiber"
  },

    # ── ASIAN DISHES ───────────────────────────────────────────────────────────
     {
    "name": "Chicken Noodle Soup",
    "category": "dinner",
    "cuisine": "Western",
    "calories": 220,
    "protein": 14.0,
    "fat": 5.0,
    "carbs": 28.0,
    "tags": ["non-vegetarian","China" , "savory", "light", "low-fat"],
    "description": "Comforting broth with chicken and noodles.",
    "image": "/images/Chicken-Noodle-Soup-Overhead.jpg",
    "why_healthy": "Hydrating and immune-supportive"
  },
  {
    "name": "Sushi (6 pcs)",
    "category": "lunch",
    "cuisine": "Asian",
    "calories": 280,
    "protein": 12.0,
    "fat": 4.0,
    "carbs": 52.0,
    "tags": ["non-vegetarian","Japan", "savory", "light", "dairy-free"],
    "description": "Assorted nigiri and maki rolls with pickled ginger.",
    "image": "/images/Sushi_platter.jpg",
    "why_healthy": "Low fat, fish provides omega-3"
  },
  {
    "name": "Ramen",
    "category": "dinner",
    "cuisine": "Asian",
    "calories": 450,
    "protein": 18.0,
    "fat": 16.0,
    "carbs": 60.0,
    "tags": ["non-vegetarian","Japan", "savory", "umami"],
    "description": "Rich broth ramen with noodles, meat, egg, and vegetables.",
    "image": "/images/HLY-Veggie-Ramen-16x9.webp",
    "why_healthy": "Comforting and protein-rich but can be high sodium"
  },
  {
    "name": "Pad Thai",
    "category": "dinner",
    "cuisine": "Asian",
    "calories": 420,
    "protein": 16.0,
    "fat": 14.0,
    "carbs": 56.0,
    "tags": ["non-vegetarian","Thailand", "savory", "tangy", "dairy-free"],
    "description": "Rice noodles stir-fried with shrimp, peanuts, and tamarind.",
    "image": "/images/Chicken-Pad-Thai_9-SQ.webp",
    "why_healthy": "Balanced carbs and protein"
  },
  {
    "name": "Chicken Fried Rice",
    "category": "dinner",
    "cuisine": "Asian",
    "calories": 400,
    "protein": 20.0,
    "fat": 14.0,
    "carbs": 54.0,
    "tags": ["non-vegetarian","China", "savory", "dairy-free"],
    "description": "Wok-fried rice with chicken, egg, and vegetables.",
    "image": "/images/Bang-Bang-Chicken-Fried-Rice-2.jpg",
    "why_healthy": "Balanced macros with vegetables"
  },
  {
    "name": "Miso Soup",
    "category": "lunch",
    "cuisine": "Asian",
    "calories": 80,
    "protein": 4.0,
    "fat": 2.0,
    "carbs": 10.0,
    "tags": ["vegetarian", "Japan","savory", "light", "dairy-free"],
    "description": "Japanese broth with tofu, seaweed, and green onions.",
    "image": "/images/Miso-Soup-8297-I-500x500.jpg",
    "why_healthy": "Low calorie, contains probiotics"
  },
  {
    "name": "Edamame",
    "category": "snack",
    "cuisine": "Asian",
    "calories": 130,
    "protein": 11.0,
    "fat": 5.0,
    "carbs": 10.0,
    "tags": ["vegetarian","China", "vegan", "savory", "light", "high-protein"],
    "description": "Steamed young soybeans lightly salted.",
    "image": "/images/Edamame.jpg",
    "why_healthy": "Complete plant protein"
  },
  {
    "name": "Bibimbap",
    "category": "dinner",
    "cuisine": "Asian",
    "calories": 480,
    "protein": 18.0,
    "fat": 14.0,
    "carbs": 70.0,
    "tags": ["non-vegetarian","South Korea" "savory", "spicy", "dairy-free"],
    "description": "Korean rice bowl with vegetables, beef, egg, and chili paste.",
    "image": "/images/Bibimbap.jpg",
    "why_healthy": "Balanced nutrients from mixed ingredients"
  },
  {
    "name": "Pho",
    "category": "dinner",
    "cuisine": "Asian",
    "calories": 320,
    "protein": 20.0,
    "fat": 7.0,
    "carbs": 45.0,
    "tags": ["non-vegetarian", "savory", "light", "dairy-free"],
    "description": "Vietnamese noodle soup with herbs and beef broth.",
    "image": "/images/Pho.webp",
    "why_healthy": "Light and hydrating"
  },
  {
    "name": "Tom Yum Soup",
    "category": "dinner",
    "cuisine": "Asian",
    "calories": 180,
    "protein": 14.0,
    "fat": 5.0,
    "carbs": 18.0,
    "tags": ["non-vegetarian", "spicy", "tangy", "light", "dairy-free"],
    "description": "Thai spicy soup with shrimp, lemongrass, and herbs.",
    "image": "/images/Tom Yum Soup.jpg",
    "why_healthy": "Low calorie and immune boosting"
  },
  {
    "name": "Tofu Stir Fry",
    "category": "dinner",
    "cuisine": "Asian",
    "calories": 260,
    "protein": 16.0,
    "fat": 11.0,
    "carbs": 24.0,
    "tags": ["vegetarian", "China","vegan", "savory", "high-protein"],
    "description": "Tofu stir-fried with vegetables and light sauce.",
    "image": "/images/Tofu Stir Fry.jpg",
    "why_healthy": "High plant protein, low saturated fat"
  },
  {
    "name": "Green Curry",
    "category": "dinner",
    "cuisine": "Asian",
    "calories": 380,
    "protein": 18.0,
    "fat": 22.0,
    "carbs": 26.0,
    "tags": ["non-vegetarian", "spicy", "savory", "dairy-free"],
    "description": "Thai coconut curry with chicken and vegetables.",
    "image": "/images/Green Curry.jpg",
    "why_healthy": "Healthy fats but calorie dense"
  },
  {
    "name": "Spring Rolls (2 pcs)",
    "category": "snack",
    "cuisine": "Asian",
    "calories": 220,
    "protein": 5.0,
    "fat": 12.0,
    "carbs": 26.0,
    "tags": ["vegetarian", "China","savory", "crispy", "dairy-free"],
    "description": "Crispy rolls filled with vegetables.",
    "image": "/images/Spring Rolls.jpg",
    "why_healthy": "Vegetable-based but fried"
  },
  {
    "name": "Wonton Soup",
    "category": "lunch",
    "cuisine": "Asian",
    "calories": 220,
    "protein": 10.0,
    "fat": 6.0,
    "carbs": 30.0,
    "tags": ["non-vegetarian", "China", "savory", "light"],
    "description": "Soup with dumplings in clear broth.",
    "image": "/images/Wonton Soup.jpg",
    "why_healthy": "Light and comforting"
  },
  {
    "name": "Vegetarian Dim Sum",
    "category": "lunch",
    "cuisine": "Asian",
    "calories": 300,
    "protein": 12.0,
    "fat": 8.0,
    "carbs": 44.0,
    "tags": ["vegetarian","Hong Kong", "savory"],
    "description": "Steamed dumplings with vegetable filling.",
    "image": "/images/Vegetarian Dim Sum.jpg",
    "why_healthy": "Steamed and moderate calories"
  },
  {
    "name": "Kung Pao Chicken",
    "category": "dinner",
    "cuisine": "Asian",
    "calories": 420,
    "protein": 26.0,
    "fat": 18.0,
    "carbs": 32.0,
    "tags": ["non-vegetarian","China", "spicy", "savory"],
    "description": "Spicy stir-fried chicken with peanuts and vegetables.",
    "image": "/images/Kung Pao Chicken.jpg",
    "why_healthy": "High protein but moderate fat"
  },
  {
    "name": "Veg Hakka Noodles",
    "category": "lunch",
    "cuisine": "Asian",
    "calories": 360,
    "protein": 10.0,
    "fat": 10.0,
    "carbs": 58.0,
    "tags": ["vegetarian", "Indo-Chinese","savory", "dairy-free"],
    "description": "Stir-fried noodles with vegetables and soy sauce.",
    "image": "/images/Veg Hakka Noodles.jpg",
    "why_healthy": "Carb-rich energy meal"
  },
  {
    "name": "Chicken Dumplings",
    "category": "snack",
    "cuisine": "Asian",
    "calories": 260,
    "protein": 18.0,
    "fat": 8.0,
    "carbs": 30.0,
    "tags": ["non-vegetarian","USA", "savory"],
    "description": "Steamed dumplings filled with minced chicken.",
    "image": "/images/Chicken Dumplings.jpg",
    "why_healthy": "Good protein, steamed option"
  },
  {
    "name": "Teriyaki Chicken",
    "category": "dinner",
    "cuisine": "Asian",
    "calories": 390,
    "protein": 30.0,
    "fat": 12.0,
    "carbs": 38.0,
    "tags": ["non-vegetarian","American creation with Japanese roots", "savory"],
    "description": "Grilled chicken glazed with sweet soy teriyaki sauce.",
    "image": "/images/Teriyaki Chicken.jpg",
    "why_healthy": "High protein, moderate carbs"
  },

    # ── MEDITERRANEAN ─────────
  {
    "name": "Hummus with Pita",
    "category": "snack",
    "cuisine": "Mediterranean",
    "calories": 300,
    "protein": 9.0,
    "fat": 14.0,
    "carbs": 36.0,
    "tags": ["vegetarian", "Levant and Egypt","vegan", "savory"],
    "description": "Creamy chickpea hummus with pita bread and olive oil.",
    "image": "/images/Hummus with Pita.jpg",
    "why_healthy": "Rich in plant protein and healthy fats"
  },
  {
    "name": "Falafel Wrap",
    "category": "lunch",
    "cuisine": "Mediterranean",
    "calories": 420,
    "protein": 13.0,
    "fat": 18.0,
    "carbs": 52.0,
    "tags": ["vegetarian","Egypt" "vegan", "savory"],
    "description": "Falafel in flatbread with tahini and vegetables.",
    "image": "/images/Falafel Wrap.jpg",
    "why_healthy": "High fiber but fried, so moderate calories"
  },
  {
    "name": "Tabbouleh",
    "category": "lunch",
    "cuisine": "Mediterranean",
    "calories": 180,
    "protein": 5.0,
    "fat": 9.0,
    "carbs": 24.0,
    "tags": ["vegetarian","Lebanon and Syria", "vegan", "light", "tangy"],
    "description": "Parsley salad with bulgur, tomatoes, and lemon.",
    "image": "/images/Tabbouleh.webp",
    "why_healthy": "Very fresh, rich in vitamins and antioxidants"
  },
  {
    "name": "Shakshuka",
    "category": "breakfast",
    "cuisine": "Mediterranean",
    "calories": 260,
    "protein": 13.0,
    "fat": 16.0,
    "carbs": 18.0,
    "tags": ["vegetarian","North Africa", "savory", "spicy", "gluten-free"],
    "description": "Eggs poached in tomato and pepper sauce.",
    "image": "/images/Shakshuka.webp",
    "why_healthy": "High protein and rich in antioxidants"
  },
  {
    "name": "Grilled Halloumi Salad",
    "category": "lunch",
    "cuisine": "Mediterranean",
    "calories": 320,
    "protein": 16.0,
    "fat": 22.0,
    "carbs": 12.0,
    "tags": ["vegetarian", "Cyprus", "savory", "gluten-free", "dairy"],
    "description": "Grilled halloumi with greens and fresh herbs.",
    "image": "/images/Grilled Halloumi Salad.jpg",
    "why_healthy": "High calcium but also high fat"
  },
  {
    "name": "Moussaka",
    "category": "dinner",
    "cuisine": "Mediterranean",
    "calories": 450,
    "protein": 20.0,
    "fat": 26.0,
    "carbs": 32.0,
    "tags": ["non-vegetarian","Greece", "savory", "dairy"],
    "description": "Layered eggplant and lamb bake with béchamel sauce.",
    "image": "/images/Moussaka.jpg",
    "why_healthy": "Rich and filling, high protein"
  },

  {
    "name": "Greek Yogurt with Honey",
    "category": "breakfast",
    "cuisine": "Mediterranean",
    "calories": 220,
    "protein": 14.0,
    "fat": 6.0,
    "carbs": 28.0,
    "tags": ["vegetarian", "sweet", "gluten-free", "dairy", "high-protein"],
    "description": "Thick Greek yogurt with honey and nuts.",
    "image": "/images/Greek Yogurt with Honey.jpg",
    "why_healthy": "Rich in probiotics and protein"
  },
  {
    "name": "Grilled Chicken Gyro",
    "category": "lunch",
    "cuisine": "Mediterranean",
    "calories": 400,
    "protein": 30.0,
    "fat": 14.0,
    "carbs": 38.0,
    "tags": ["non-vegetarian","Greek", "savory"],
    "description": "Grilled chicken in pita with tzatziki and vegetables.",
    "image": "/images/Grilled Chicken Gyro.jpg",
    "why_healthy": "High protein and balanced macros"
  },
  {
    "name": "Lentil Salad",
    "category": "lunch",
    "cuisine": "Mediterranean",
    "calories": 260,
    "protein": 14.0,
    "fat": 8.0,
    "carbs": 36.0,
    "tags": ["vegetarian","France", "vegan", "light", "high-protein"],
    "description": "Lentils with olive oil, herbs, and vegetables.",
    "image": "/images/Lentil Salad.jpg",
    "why_healthy": "High fiber and plant protein"
  },
  {
    "name": "Stuffed Grape Leaves (Dolma)",
    "category": "snack",
    "cuisine": "Mediterranean",
    "calories": 200,
    "protein": 6.0,
    "fat": 8.0,
    "carbs": 28.0,
    "tags": ["vegetarian", "Turkish", "vegan", "savory"],
    "description": "Rice and herbs wrapped in grape leaves.",
    "image": "/images/Stuffed Grape Leaves (Dolma).jpg",
    "why_healthy": "Light and rich in herbs"
  },
  {
    "name": "Grilled Fish with Olive Oil",
    "category": "dinner",
    "cuisine": "Mediterranean",
    "calories": 320,
    "protein": 34.0,
    "fat": 16.0,
    "carbs": 4.0,
    "tags": ["non-vegetarian", "gluten-free", "dairy-free", "high-protein"],
    "description": "Simple grilled fish with olive oil and herbs.",
    "image": "/images/Grilled Fish with Olive Oil.webp",
    "why_healthy": "High omega-3 and lean protein"
  },
  {
    "name": "Vegetable Ratatouille",
    "category": "dinner",
    "cuisine": "Mediterranean",
    "calories": 220,
    "protein": 6.0,
    "fat": 10.0,
    "carbs": 28.0,
    "tags": ["vegetarian", "France","vegan", "light", "dairy-free"],
    "description": "Stewed vegetables with herbs and olive oil.",
    "image": "/images/Vegetable Ratatouille.jpg",
    "why_healthy": "Low calorie, high in antioxidants"
  },

    #----------Desserts-------------------
  {
    "name": "Gulab Jamun (2 pcs)",
    "category": "dessert",
    "cuisine": "Indian",
    "calories": 300,
    "protein": 5.0,
    "fat": 12.0,
    "carbs": 45.0,
    "tags": ["vegetarian", "sweet", "dairy"],
    "description": "Deep-fried milk dumplings soaked in sugar syrup.",
    "image": "/images/Gulab Jamun.jpg",
    "why_healthy": "Energy-dense treat, best in moderation"
  },
  {
    "name": "Kheer (Rice Pudding)",
    "category": "dessert",
    "cuisine": "Indian",
    "calories": 260,
    "protein": 8.0,
    "fat": 10.0,
    "carbs": 36.0,
    "tags": ["vegetarian", "sweet", "dairy", "gluten-free"],
    "description": "Creamy rice pudding with milk, cardamom, and nuts.",
    "image": "/images/Kheer.webp",
    "why_healthy": "Provides calcium and energy"
  },
  {
    "name": "Brownie",
    "category": "dessert",
    "cuisine": "Western",
    "calories": 320,
    "protein": 4.0,
    "fat": 18.0,
    "carbs": 38.0,
    "tags": ["vegetarian", "sweet", "dairy"],
    "description": "Dense chocolate brownie with rich texture.",
    "image": "/images/Brownie.jpg",
    "why_healthy": "High calorie treat"
  },
  {
    "name": "Greek Yogurt with Berries",
    "category": "dessert",
    "cuisine": "Mediterranean",
    "calories": 180,
    "protein": 12.0,
    "fat": 4.0,
    "carbs": 24.0,
    "tags": ["vegetarian", "sweet", "light", "gluten-free", "dairy", "high-protein"],
    "description": "Creamy yogurt topped with berries and honey.",
    "image": "/images/Greek Yogurt with Berries.jpg",
    "why_healthy": "High protein and probiotics"
  },
  {
    "name": "Baklava",
    "category": "dessert",
    "cuisine": "Mediterranean",
    "calories": 330,
    "protein": 6.0,
    "fat": 20.0,
    "carbs": 34.0,
    "tags": ["vegetarian", "sweet", "dairy"],
    "description": "Layered pastry with nuts and honey syrup.",
    "image": "/images/Baklava.jpg",
    "why_healthy": "Rich in nuts but high sugar"
  },
  {
    "name": "Mango Sorbet",
    "category": "dessert",
    "cuisine": "Global",
    "calories": 160,
    "protein": 1.0,
    "fat": 0.5,
    "carbs": 38.0,
    "tags": ["vegetarian", "vegan", "sweet", "dairy-free", "gluten-free"],
    "description": "Frozen mango puree dessert.",
    "image": "/images/Mango Sorbet.jpg",
    "why_healthy": "Low fat, refreshing fruit-based dessert"
  },
  {
    "name": "Rasgulla (2 pcs)",
    "category": "dessert",
    "cuisine": "Indian",
    "calories": 220,
    "protein": 6.0,
    "fat": 5.0,
    "carbs": 36.0,
    "tags": ["vegetarian", "sweet", "dairy", "gluten-free"],
    "description": "Soft paneer balls soaked in sugar syrup.",
    "image": "/images/Rasgulla.webp",
    "why_healthy": "Lower fat than fried sweets"
  },

    # ── HIGH-PROTEIN SPECIALS ──────────────────────────────────────────────────
  {
    "name": "Protein Smoothie",
    "category": "breakfast",
    "cuisine": "Western",
    "calories": 320,
    "protein": 30.0,
    "fat": 7.0,
    "carbs": 34.0,
    "tags": ["vegetarian", "sweet", "high-protein", "gluten-free"],
    "description": "Whey protein smoothie with banana, oats, and almond milk.",
    "image": "/images/Protein Smoothie.jpg",
    "why_healthy": "Supports muscle recovery and provides sustained energy"
  },
  {
    "name": "Boiled Eggs (6 pcs)",
    "category": "breakfast",
    "cuisine": "Western",
    "calories": 441,
    "protein": 37,
    "fat": 29,
    "carbs": 2.0,
    "tags": ["non-vegetarian", "savory", "gluten-free", "dairy-free", "high-protein"],
    "description": "Hard or soft boiled eggs, rich in essential nutrients.",
    "image": "/images/Boiled Eggs.jpg",
    "why_healthy": "Complete protein with essential vitamins and choline"
  },
  {
    "name": "Cottage Cheese Bowl",
    "category": "breakfast",
    "cuisine": "Western",
    "calories": 180,
    "protein": 22.0,
    "fat": 5.0,
    "carbs": 12.0,
    "tags": ["vegetarian", "savory", "light", "gluten-free", "dairy", "high-protein"],
    "description": "Low-fat cottage cheese with fresh vegetables and herbs.",
    "image": "/images/Cottage Cheese Bowl.jpg",
    "why_healthy": "High protein and low calorie, great for weight management"
  },

    # ── LOW-CALORIE OPTIONS ────────────────────────────────────────────────────
  {
    "name": "Cucumber Salad",
    "category": "snack",
    "cuisine": "Western",
    "calories": 70,
    "protein": 1.5,
    "fat": 3.0,
    "carbs": 9.0,
    "tags": ["vegetarian", "vegan", "tangy", "light", "gluten-free", "dairy-free"],
    "description": "Sliced cucumber with dill, vinegar, and red onion.",
    "image": "/images/Cucumber Salad.jpg",
    "why_healthy": "Very low calorie and highly hydrating"
  },
  {
    "name": "Steamed Broccoli",
    "category": "snack",
    "cuisine": "Western",
    "calories": 55,
    "protein": 3.5,
    "fat": 0.8,
    "carbs": 9.0,
    "tags": ["vegetarian", "vegan", "light", "gluten-free", "dairy-free"],
    "description": "Steamed broccoli florets with a pinch of salt.",
    "image": "/images/Steamed Broccoli.jpg",
    "why_healthy": "Rich in vitamin C, fiber, and antioxidants"
  },
  {
    "name": "Zucchini Noodles",
    "category": "dinner",
    "cuisine": "Western",
    "calories": 160,
    "protein": 4.0,
    "fat": 7.0,
    "carbs": 18.0,
    "tags": ["vegetarian", "vegan", "light", "gluten-free", "dairy-free"],
    "description": "Spiralized zucchini with light marinara or pesto.",
    "image": "/images/Zucchini Noodles.jpg",
    "why_healthy": "Low-carb alternative to pasta, nutrient-rich"
  },
  {
    "name": "Cauliflower Rice Bowl",
    "category": "dinner",
    "cuisine": "Western",
    "calories": 130,
    "protein": 4.0,
    "fat": 5.0,
    "carbs": 16.0,
    "tags": ["vegetarian", "vegan", "light", "gluten-free", "dairy-free"],
    "description": "Cauliflower rice stir-fried with vegetables and spices.",
    "image": "/images/Cauliflower Rice Bowl.webp",
    "why_healthy": "Low calorie and low carb, high in fiber"
  },

    # ── SNACKS & DESSERTS ─────────────────────────────────────────────────────
     {
    "name": "Fruit Salad",
    "category": "dessert",
    "cuisine": "Global",
    "calories": 120,
    "protein": 2.0,
    "fat": 1.0,
    "carbs": 28.0,
    "tags": ["vegetarian", "vegan", "sweet", "light", "gluten-free", "dairy-free"],
    "description": "Fresh seasonal fruits mixed together.",
    "image": "/images/Fruit Salad.jpg",
    "why_healthy": "Rich in vitamins and fiber"
  },
  {
    "name": "Mixed Nuts",
    "category": "snack",
    "cuisine": "Western",
    "calories": 600,
    "protein": 20.0,
    "fat": 54.0,
    "carbs": 20.0,
    "tags": ["vegetarian", "vegan", "savory", "gluten-free", "dairy-free", "nuts"],
    "description": "Roasted almonds, cashews, walnuts, and pistachios.",
    "image": "/images/Mixed Nuts.webp",
    "why_healthy": "Rich in healthy fats, vitamin E, and minerals"
  },
  {
    "name": "Dark Chocolate",
    "category": "dessert",
    "cuisine": "Western",
    "calories": 550,
    "protein": 6.0,
    "fat": 35.0,
    "carbs": 50.0,
    "tags": ["vegetarian", "vegan", "sweet", "dairy-free"],
    "description": "70%+ cocoa dark chocolate.",
    "image": "/images/Dark Chocolate.jpg",
    "why_healthy": "Contains antioxidants, best in moderation"
  },
  {
    "name": "Banana Smoothie",
    "category": "snack",
    "cuisine": "Western",
    "calories": 90,
    "protein": 2.0,
    "fat": 1.0,
    "carbs": 22.0,
    "tags": ["vegetarian", "vegan", "sweet", "gluten-free", "dairy-free"],
    "description": "Blended banana with plant-based milk.",
    "image": "/images/Banana Smoothie.webp",
    "why_healthy": "Natural energy source rich in potassium"
  },
  {
    "name": "Protein Bar",
    "category": "snack",
    "cuisine": "Western",
    "calories": 450,
    "protein": 35.0,
    "fat": 15.0,
    "carbs": 35.0,
    "tags": ["vegetarian", "sweet", "high-protein", "gluten-free"],
    "description": "Whey-based protein bar with oats and chocolate coating.",
    "image": "/images/Protein Bar.webp",
    "why_healthy": "Convenient high-protein snack"
  },
  {
    "name": "Apple with Almond Butter",
    "category": "snack",
    "cuisine": "Western",
    "calories": 180,
    "protein": 4.0,
    "fat": 9.0,
    "carbs": 22.0,
    "tags": ["vegetarian", "vegan", "sweet", "savory", "gluten-free", "dairy-free", "nuts"],
    "description": "Fresh apple slices with almond butter.",
    "image": "/images/Apple with Almond Butter.jpg",
    "why_healthy": "Good balance of fiber and healthy fats"
  },
  {
    "name": "Guacamole with Veggie Sticks",
    "category": "snack",
    "cuisine": "Western",
    "calories": 160,
    "protein": 2.0,
    "fat": 14.0,
    "carbs": 9.0,
    "tags": ["vegetarian", "vegan", "savory", "gluten-free", "dairy-free"],
    "description": "Avocado dip served with fresh vegetable sticks.",
    "image": "/images/Guacamole with Veggie Sticks.jpg",
    "why_healthy": "Rich in heart-healthy fats and nutrients"
  },

        #----------High Calorie---------
  {
    "name": "Loaded Deep-Dish Pizza (Extra Cheese & Meat Feast)",
    "category": "dinner",
    "cuisine": "Western",
    "total_calories": 4000,
    "protein": 85.0,
    "fat": 95.0,
    "carbs": 160.0,
    "serving_size": "1 large pizza (12 inch, heavy toppings)",
    "tags": ["non-vegetarian", "high-calorie", "cheesy", "party-food"],
    "description": "Deep-dish pizza loaded with cheese, pepperoni, sausage, and extra crust butter.",
    "image": "/images/Loaded Deep-Dish Pizza (Extra Cheese & Meat Feast).webp",
    "why_healthy": "High energy meal, suitable for bulking or cheat meals"
  },
  {
    "name": "Chicken & Mushroom Cream Pasta (Large Bowl)",
    "category": "dinner",
    "cuisine": "Western",
    "total_calories": 1100,
    "protein": 60.0,
    "fat": 45.0,
    "carbs": 120.0,
    "serving_size": "1 large restaurant bowl (~400–500g)",
    "tags": ["non-vegetarian", "creamy", "high-calorie"],
    "description": "Creamy pasta with grilled chicken, mushrooms, butter, and parmesan sauce.",
    "image": "/images/Chicken & Mushroom Cream Pasta (Large Bowl).jpg",
    "why_healthy": "Balanced macros, good for muscle gain"
  },
  {
    "name": "Chicken Biryani (Full Plate)",
    "category": "dinner",
    "cuisine": "Indian",
    "total_calories": 1300,
    "protein": 55.0,
    "fat": 50.0,
    "carbs": 150.0,
    "serving_size": "1 full plate (restaurant style)",
    "tags": ["non-vegetarian", "aromatic", "high-calorie"],
    "description": "Fragrant basmati rice cooked with chicken, ghee, and spices.",
    "image": "/images/Chicken Biryani (Full Plate).jpg",
    "why_healthy": "High protein + carb dense energy meal"
  },
  {
    "name": "Butter Chicken with Naan Combo",
    "category": "dinner",
    "cuisine": "Indian",
    "total_calories": 1200,
    "protein": 60.0,
    "fat": 70.0,
    "carbs": 90.0,
    "serving_size": "1 curry bowl + 2 butter naan",
    "tags": ["non-vegetarian", "creamy", "high-calorie"],
    "description": "Creamy butter chicken served with buttery naan bread.",
    "image": "/images/Butter Chicken with Naan Combo.jpg",
    "why_healthy": "High protein but also rich in fats"
  },
  {
    "name": "Paneer Butter Masala Thali",
    "category": "lunch",
    "cuisine": "Indian",
    "total_calories": 1000,
    "protein": 35.0,
    "fat": 65.0,
    "carbs": 80.0,
    "serving_size": "Paneer curry + rice + naan + sides",
    "tags": ["vegetarian", "high-calorie", "dairy"],
    "description": "Rich paneer curry meal with rice, naan, and sides.",
    "image": "/images/Paneer Butter Masala Thali.jpg",
    "why_healthy": "Energy dense vegetarian protein meal"
  },
  {
    "name": "Full Sushi Party Platter",
    "category": "lunch",
    "cuisine": "Asian",
    "total_calories": 2000,
    "protein": 90.0,
    "fat": 40.0,
    "carbs": 300.0,
    "serving_size": "40–50 pieces assorted sushi",
    "tags": ["non-vegetarian", "high-calorie", "seafood"],
    "description": "Large sushi platter with salmon, tuna, shrimp, and rolls.",
    "image": "/images/Full Sushi Party Platter.jpg",
    "why_healthy": "High protein and omega-3 rich meal"
  },
  {
    "name": "Chocolate Cake Celebration Slice (Whole Cake Portion)",
    "category": "dessert",
    "cuisine": "Western",
    "total_calories": 2200,
    "protein": 25.0,
    "fat": 120.0,
    "carbs": 260.0,
    "serving_size": "Half or full medium cake",
    "tags": ["vegetarian", "sweet", "high-calorie"],
    "description": "Rich layered chocolate cake with frosting and cream.",
    "image": "/images/Chocolate Cake Celebration Slice (Whole Cake Portion).webp",
    "why_healthy": "High sugar energy dense dessert"
  },
  {
    "name": "Ice Cream Sundae MegaBowl",
    "category": "dessert",
    "cuisine": "Western",
    "total_calories": 1200,
    "protein": 15.0,
    "fat": 70.0,
    "carbs": 130.0,
    "serving_size": "Large sundae bowl with toppings",
    "tags": ["vegetarian", "sweet", "dairy"],
    "description": "Ice cream with syrup, nuts, brownie, and whipped cream.",
    "image": "/images/Ice Cream Sundae Mega Bowl.jpg",
    "why_healthy": "High energy dessert, very high sugar"
  }
]
